
%==========================================================================
% Codes needed for generation of:
% * gpr image data which is enlarged,whitened, normalized, and selectable
% filtered.
% * Sift Features which is generated by vlfeat implementation.
% * descriptor vector corresponding to an image file of gpr data based on
%  SIFT feature counts in cells grid.
% * Feature vectors belonging to each cell, in matlab cell format.
% 
%--------------------------------------------------------------------------

clear all, clc, close all,

curDir = pwd;
idcs   = strfind(curDir,'\');
rootDir = curDir(1:idcs(end)-1);
gprDir = strcat(rootDir, '\','gpr Generated Files');
imgPath = strcat(gprDir, '\','20-Demo Image');


imgCode = input('Enter out-file name (in 20-Demo Image) to process\n>>');
% Entery example : 'DST_Ref_3111.out'
% imgCode = 'DST_Ref_3111.out';

[gprImg] = read_gpr_img(imgCode, imgPath);

mean = 0; 
var = 0.0;
[feature] = find_SIFT(gprImg, 'addnoise', 'gaussian', mean, var);
%[feature] = find_SIFT_v1_1(gprImg, 'gaussian', mean, var);

xUpLeft = 23;
yUpLeft = 80;

% xUpLeft = 35;
% yUpLeft = 80;

[descriptor, fInRec] = create_single_desc(feature, xUpLeft, yUpLeft);

% -------------------------------------------------------------------------
% Visualization of descrtiptors on gpr data.
% -------------------------------------------------------------------------
show_desc(fInRec, xUpLeft, yUpLeft)

%==========================================================================                    
                    






